config/routes.rb
Rails.application.routes.draw do

  resources :collaborators, only: [:show]

  resources :wikis
  resources :wikis, only: [] do
    resources :collaborators, only: [:index, :create, :destroy]
  end

  devise_for :users #, controllers: { registrations: 'users/registrations' }

  resources :charges, only: [:new, :create] do
    collection do
      get 'downgrade'
    end

  end

  get 'welcome/index'
  root 'welcome#index'

end

app/models/collaborator.rb
class Collaborator < ActiveRecord::Base
  belongs_to :user
  belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:admin, :standard, :premium]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :standard
  end
  has_many :wikis, dependent: :destroy
  has_many :collaborators
  has_many :collaborating_wikis, through: :collaborators, source: :wiki

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :confirmable, :database_authenticatable, :registerable,
    :recoverable, :rememberable, :trackable, :validatable


  validates :username, presence: true
  validates :username, uniqueness: true, if: -> { self.username.present? }


  

end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborators 

  has_many :collaborating_users, through: :collaborators, source: :user
  validates :title, presence: true
  validates :body,  presence: true
  #validates :private, presence: true
  validates :user, presence: true

  def collaborator_for(user_id)
    collaborators.find_by(user_id: user_id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


  include Pundit
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username])

  end

  def user_not_authorized(exception)
    policy_name = exception.policy.class.to_s.underscore

    flash[:alert] = t "#{policy_name}.#{exception.query}", scope: "pundit", default: :default
    redirect_to(request.referrer || root_path)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController


  def new
    if user_signed_in?
      @stripe_btn_data = {
        key: "#{ Rails.configuration.stripe[:publishable_key] }",
        #key: "pk_test_z3971ulOJS1heFJXHUYprE5Z",
        description: "Premium Blocipedia Subscription - #{current_user.username}",
        amount: 19_00 #Amount.default
      }
    else
      redirect_to root_path
      flash[:notice] = "You must be signed in to do that."
    end
  end

  def create
    # Creates a Stripe Customer object, for associating
    # with the charge
    customer = Stripe::Customer.create(
      email: current_user.email,
      card: params[:stripeToken]
    )

    # Where the real magic happens
    charge = Stripe::Charge.create(
      customer: customer.id, # Note -- this is NOT the user_id in your app
      amount: 19_00,
      description: "Premium Blocipedia Subscription - #{current_user.email}",
      currency: 'usd'
    )

    current_user.update_attributes!(role: 'premium')

    flash[:notice] = "Thanks for signing up for Blocipedia Premium, #{current_user.email}!"
    redirect_to edit_user_registration_path # or wherever

    # Stripe will send back CardErrors, with friendly messages
    # when something goes wrong.
    # This `rescue block` catches and displays those errors.
  rescue Stripe::CardError => e
    flash[:alert] = e.message
    redirect_to new_charge_path
  end

  def downgrade
    #cancel sub
    current_user.update_attributes!(role: 'standard')
    Wiki.where(user_id: current_user.id, private: true).update_all(private: false)
    redirect_to edit_user_registration_path(current_user)
  end

end

app/controllers/collaborators_controller.rb
class CollaboratorsController < ApplicationController
  
  def index
    @wiki = Wiki.find(params[:wiki_id])
    @users = User.all
  end

  def show
    @collaborator = Collaborator.find(params[:id])
  end

  def create
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.build 
    @collaborator.user_id = params[:user_id]

    if @collaborator.save
      flash[:notice] = "You Added a collaborator"
    else
      flash[:alert] = "Was not about to add collaborator. Please try again"
    end
    redirect_to wiki_path(@wiki)
  end

  def destroy
    @wiki = Wiki.find(params[:wiki_id])
    @collaborator = @wiki.collaborators.find(params[:id])

    if @collaborator.destroy
      flash[:notice] = "Collaborator was deleted successfully."
    else
      flash[:alert] = "Collaborator couldn't be deleted. Try again."
    end
    redirect_to wiki_collaborators_path(@wiki)

  end

  def collaborator_params
    params.require(:collaborator).permit(:user_id, :wiki_id)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def show
    @wiki = Wiki.find(params[:id])
  end

  def index
    @wikis = policy_scope(Wiki)
  end

  def new
    @wiki = Wiki.new
    authorize @wiki
  end

  def create
    @wiki = current_user.wikis.build(wiki_params)
    authorize @wiki

    #@wiki = Wiki.new(wiki_params)
    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash.now[:alert] = "Error creating wiki. Please try again."
      render :new
    end
  end

  def edit
    @wiki = Wiki.find(params[:id])
  end

  def update
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    @wiki.assign_attributes(wiki_params)

    if @wiki.save
      redirect_to @wiki, notice: "Wiki was saved successfully."
    else
      flash.now[:alert] = "Error saving wiki. Please try again."
      render :edit
    end
  end

  def destroy
    @wiki = Wiki.find(params[:id])
    authorize @wiki

    if @wiki.destroy
      flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
      redirect_to action: :index
    else
      flash.now[:alert] = "There was an error deleting the wiki."
      render :show
    end
  end


  private

  def wiki_params
    params.require(:wiki).permit(:title, :body, :private, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def stripe_btn_data
    @stripe_btn_data ||= {
      key: "#{ Rails.configuration.stripe[:publishable_key] }",
      description: "Premium Blocipedia Subscription - #{current_user.username}",
      amount: 19_00 #Amount.default
    }
  end
  

  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true, 
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true, 
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/users_helper.rb
module UsersHelper
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/_downgrade.html.erb
<h4>Downgrade To Standard Plan</h4>
<%= link_to 'Downgrade Membership', downgrade_charges_path, data:  { confirm: 'All your private wikis will be made public. Are you sure you want to downgrade?' }, class: 'btn btn-primary btn-lg' %>

app/views/charges/new.html.erb
<% if current_user.premium? %>
	<h3>Current Plan: Premium Plan</h3>
  <%= render partial: "charges/downgrade" %>
<% else %>
	<h3>Current Plan: Free Plan</h3>
	<h4>Upgrade to Premium</h4>
	<p>Upgrade to the premium plan and create as many private wikis as you want!</p>
	<%= form_tag charges_path do %>
		<script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= stripe_btn_data[:key] %>" data-amount=<%= stripe_btn_data[:amount] %> data-description="<%= stripe_btn_data[:description] %>" ></script>
	<% end %>
<% end %>

app/views/collaborators/_collaborators.html.erb
<div class="row">
	<div class="col-md-8">
		<h3>Collaborators for <%= @wiki.title %></h3>
		<!-- #29 -->
		<% @wiki.collaborating_users.each do |user| %>
			<div class="row">
				<div class="col-md-3">
					<% if @wiki.collaborating_users.include? user %>
						<%= user.email %>
					<% end %>
				</div>
			</div>
		<% end %>
		<br />
		<%= link_to "Add/Remove Collaborators", wiki_collaborators_path(@wiki.id), class: "btn btn-primary" %>
	</div>
</div>

app/views/collaborators/_form.html.erb
<%= form_for(wiki) do |f| %>
	<div class="form-group">
	  <%= f.label :collaborator %>
	  <%= f.select :user_id, options_from_collection_for_select(User.all, "id", "username") %>
	  <%= f.submit "Save", class: 'btn btn-default' %>
	</div>

<% end %>

app/views/collaborators/index.html.erb
<div class="row">
	<div class="col-md-8">
		<h1>Collaborators for <%= @wiki.title %></h1>
		<!-- #29 -->
		<% @users.each do |user| %>
			<div class="row">
				<div class="col-md-1">
					<%= user.id %>
				</div>
				<div class="col-md-3">
					<%= user.email %>
				</div>
				<div class="col-md-3">
					<% if @wiki.collaborating_users.include? user %>
						<%= button_to "Remove Collaborator", wiki_collaborator_path(@wiki.id, @wiki.collaborator_for(user.id)), method: :delete, class: "btn btn-danger" %>
					<% else %>
						<%= button_to "Add as Collaborator", wiki_collaborators_path(@wiki.id, user_id: user.id), method: :post, class: "btn btn-success" %>
					<% end %>
				</div>
			</div>
		<% end %>
		
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>Blocipedia</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<%= stylesheet_link_tag    "application", media: "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
	</head>
	<body>
	<div class="container">
		<div class="row">
		<div class="header-sign-in">
		<% if user_signed_in? %>
			  Signed in as: <strong><%= current_user.email %></strong>
			   <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link navbar-right'  %>
			   <%= link_to 'Profile', edit_user_registration_path, :class => 'navbar-link navbar-right' %>
			<% else %>
			  <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link navbar-right'  %>
			  <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link navbar-right'  %>
			<% end %>
		</div>	
     <ul class="nav nav-tabs">
			<li><%= link_to "Home", welcome_index_path %></li>
			<li><%= link_to "Wikis", wikis_path %></li>
			</ul>
			
		</div>
	</div>
	<div class="container">
	  <div class="row">
	  <% if flash[:notice] %>
       <div class="alert alert-success">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:notice] %>
       </div>
     <% elsif flash.now[:alert] %>
       <div class="alert alert-danger">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash.now[:alert] %>
       </div>
     <% elsif flash[:alert] %>
       <div class="alert alert-warning">
         <button type="button" class="close" data-dismiss="alert">&times;</button>
         <%= flash[:alert] %>
       </div>
     <% end %>
			<%= yield %>
		</div>
	</div>
	</body>
</html>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<div class="jumbotron">
<h2>Blocipedia: Social, Markdown Wikis</h1>
<p>Create and share Markdown Wikis</p>
<%= button_to 'Sign Up', new_user_registration_path, class: 'btn btn-primary btn-lg' %>
</div>
<div class="col-sm-6">
<p> Create as man public wikis as you want!</p>
<h4> Free Plan</h4>
</div>
<div class="col-sm-6">
<p> Create private wikis!</p>
<h4> Premium Plan</h4>
</div>

app/views/wikis/_wiki.html.erb
<div class="media">
    <div class="media-body">
        <h4 class="media-heading">
        <!-- #8 -->
        <%= link_to wiki.title, wiki %>
        </h4>
       
    </div>
</div>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wik body" %>
    </div>
    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <!-- #11 -->
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
      <div class="row">
        <div class="col-md-8">
            <%= render partial: "collaborators/collaborators" %>
            <br />
        </div>
      </div>
    <% end %>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/wikis/index.html.erb
<h1>My Wikis</h1>

<div class="row">
  
    <!-- #7 -->
    <% @wikis.each do |wiki| %>
    	<div class="col-md-8">
      <%= render wiki %>
      </div>
      <div class="col-md-4">
      <% if current_user %>
		  	<%= link_to "Edit Wiki", edit_wiki_path(wiki), class: 'btn btn-success' %>
		  	<% if policy(wiki).destroy? %>
      		<%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
      	<% end %>
			<% end %>
			</div>
    <% end %>
<div class="row">
  <div class="col-md-8">
		<% if policy(Wiki.new).new? %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
    <% end %>

  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>

<div class="row">
  <div class="col-md-8">
    <%= form_for @wiki do |f| %>
    <div class="form-group">
      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki name" %>
    </div>
    <div class="form-group">
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
    </div>
    <% if current_user.admin? || current_user.premium? %>
      <div class="form-group">
        <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
        <% end %>
      </div>
    <% end %>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/wikis/show.html.erb
<h1><%= @wiki.title %></h1>

<% if current_user %>
  <%= link_to "Edit Wiki", edit_wiki_path, class: 'btn btn-success' %>
<% end %>
<div class="row">
  <div class="col-md-8">
    <p class="lead">
      <%= markdown(@wiki.body) %>
    </p>
    <p class="lead">
      <strong>Private:</strong> <%= @wiki.private %>
    </p>
  </div>
  <% if current_user %>
    <div class="col-md-4">
      <% if policy(Wiki.new).new? %>
      <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
      <% end %>
      <% if policy(@wiki).destroy? %>
      <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?' } %>
      <% end %>
    </div>
  <% end %> 
</div>
<div class="row">
  <div class="col-md-8">
      <%= render partial: "collaborators/collaborators" %>
  </div>
</div>